// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zjP_oMPyUWET0_qTWJFtbztEmD0vOwI',
    appId: '1:734804270503:web:5150ea382058b7c26e2a82',
    messagingSenderId: '734804270503',
    projectId: 'audiotales-18ca4',
    authDomain: 'audiotales-18ca4.firebaseapp.com',
    storageBucket: 'audiotales-18ca4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiMYOEf7mxoyaWRLwlBuGNo1F6ioEOWM',
    appId: '1:734804270503:android:430467f7b49d98f96e2a82',
    messagingSenderId: '734804270503',
    projectId: 'audiotales-18ca4',
    storageBucket: 'audiotales-18ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_pWxAPGpaSPewP7oPMrchTvtKUJyhG4',
    appId: '1:734804270503:ios:4a7bcab9fb353ea26e2a82',
    messagingSenderId: '734804270503',
    projectId: 'audiotales-18ca4',
    storageBucket: 'audiotales-18ca4.appspot.com',
    androidClientId:
        '734804270503-1vtivg178ooermr850fdtgao03ii9dmj.apps.googleusercontent.com',
    iosClientId:
        '734804270503-30vo32n7i83dsj4b3j0kb0l72kptb984.apps.googleusercontent.com',
    iosBundleId: 'audiotale',
  );
}
